### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by miu200521358** [zju3dv/4K4D#11]
Hi. Allow me to thank you for the other day's support.

I was trying out `Rendering With Minimal Dataset (Only Encoded Videos)` using the script file you provided, but I encountered  `RuntimeError: CUDA out of memory`. However, the memory size displayed `under Including non-PyTorch memory` is a very large `17179869184.00 GiB`, so I'm not sure if my PC's GPU is insufficient or if I've made some mistake in the settings. Is it possible to run 4K4D on a GPU with 8GB of memory?

### Environment

- OS: Ubuntu 22.04.3 LTS (Windows11 Pro WSL2)
- Anaconda: conda 23.7.4
- GPU: NVIDIA GeForce RTX 3060 Ti (Memory 8GB)

### Command

```
python scripts/realtime4dv/extract_images.py --data_root data/renbody/0012_01
python scripts/realtime4dv/extract_masks.py --data_root data/renbody/0012_01

evc -t gui -c configs/projects/realtime4dv/rendering/4k4d_0012_01.yaml,configs/specs/video.yaml
```

### Log

```
(easyvolcap) miu@garnet:~/mmd/4K4D$ evc -t gui -c configs/projects/realtime4dv/rendering/4k4d_0012_01.yaml,configs/specs/video.yaml
2023-12-23 08:46:38.110584 easyvolcap.scripts.main -> preflight: Starting experiment: 4k4d_0012_01, command:  main.py:80                           gui
2023-… easyv… Loading mask bytes for data/renbody/0012_01/masks_libx265 VAL 100% ━━━━━━ 9,000… 0:00:… < 0:00:… 170.9  p…08:47… ->                                                                                                      it/s
       load_…
2023-… easyv… Loading imgs bytes for data/renbody/0012_01/images_libx265 VAL 100% ━━━━━━ 9,000… 0:01:… < 0:00… 46.42  p…08:49… ->                                                                                                      it/s
       load_…
2023-12… easyvol… Cropping msks imgs for data/renbody/0012_01 VAL 100% ━━━━━━━━━ 9,000/9… 0:00:34 < 0:00:00 252.9     p…08:49:3… ->                                                                                                 it/s
         decode_…
2023-12-23 08:49:41.726240 easyvolcap.runners.visualizers.volumetric_video_visualizer  volumetric_video_visualizer.py:76                           -> __init__: Visualization output:
                           data/result/4k4d_0012_01/{RENDER,DEPTH}
2023-12-23 08:49:41.728334 easyvolcap.runners.recorders -> __init__: Saved config file to               recorders.py:105                           data/record/4k4d_0012_01/4k4d_0012_01_1703288981.yaml
2023-12-23 08:49:45.815186 easyvolcap.utils.console_utils -> inner: Runtime exception: The          console_utils.py:337                           following operation failed in the TorchScript interpreter.
                           Traceback of TorchScript (most recent call last):
                             File "/home/miu/mmd/4K4D/easyvolcap/utils/enerf_utils.py", line 94, in
                           sample_geometry_feature_image
                               # -> B, S, P, 4
                               xyz1 = (xyz1[..., None, :, :] @ src_exts.mT)
                               xyzs = xyz1[..., :3] @ src_ixts.mT  # B, S, P, 3 @ B, S, 3, 3
                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
                               xy = xyzs[..., :-1] / (xyzs[..., -1:] + 1e-8)  # B, S, P, 2
                               x, y = xy.chunk(2, dim=-1)  # B, S, P, 1
                           RuntimeError: CUDA out of memory. Tried to allocate 180.00 MiB. GPU 0
                           has a total capacty of 8.00 GiB of which 0 bytes is free. Including
                           non-PyTorch memory, this process has 17179869184.00 GiB memory in use.
                           Of the allocated memory 7.80 GiB is allocated by PyTorch, and 89.26 MiB
                           is reserved by PyTorch but unallocated. If reserved but unallocated
                           memory is large try setting max_split_size_mb to avoid fragmentation.
                           See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮│ /home/miu/mmd/4K4D/easyvolcap/utils/console_utils.py:334 in inner                                                    ││                                                                                                                      ││ ❱ 334 │   │   │   return func(*args, **kwargs)                                                                       ││                                                                                                                      ││ /home/miu/mmd/4K4D/easyvolcap/engine/registry.py:56 in inner                                                         ││                                                                                                                      ││ ❱  56 │   │   return call_from_cfg(func, cfg)                                                                        ││                                                                                                                      ││ /home/miu/mmd/4K4D/easyvolcap/engine/registry.py:47 in call_from_cfg                                                 ││                                                                                                                      ││ ❱  47 │   return func(**call_args)                                                                                   ││                                                                                                                      ││ /home/miu/mmd/4K4D/easyvolcap/scripts/main.py:119 in gui                                                             ││                                                                                                                      ││ ❱ 119 │   viewer: "VolumetricVideoViewer" = RUNNERS.build(viewer_cfg, runner=runner)  # will start the window        ││                                                                                                                      ││ /home/miu/mmd/4K4D/easyvolcap/engine/registry.py:300 in build                                                        ││                                                                                                                      ││ ❱ 300 │   │   return self.build_func(*args, **kwargs, registry=self)                                                 ││                                                                                                                      ││ /home/miu/mmd/4K4D/easyvolcap/engine/registry.py:131 in build_from_cfg                                               ││                                                                                                                      ││ ❱ 131 │   return call_from_cfg(obj_cls, args)                                                                        ││                                                                                                                      ││ /home/miu/mmd/4K4D/easyvolcap/engine/registry.py:47 in call_from_cfg                                                 ││                                                                                                                      ││ ❱  47 │   return func(**call_args)                                                                                   ││                                                                                                                      ││ /home/miu/mmd/4K4D/easyvolcap/runners/volumetric_video_viewer.py:113 in __init__                                     ││                                                                                                                      ││ ❱  113 │   │   self.epoch = self.runner.load_network()  # load weights only (without optimizer states)               ││                                                                                                                      ││ /home/miu/mmd/4K4D/easyvolcap/runners/volumetric_video_runner.py:179 in load_network                                 ││                                                                                                                      ││ ❱ 179 │   │   epoch = load_network(model=self.model,  # only loading the network, without recorder?                  ││                                                                                                                      ││ /home/miu/mmd/4K4D/easyvolcap/utils/net_utils.py:2657 in load_network                                                ││                                                                                                                      ││ ❱ 2657 │   (model if not isinstance(model, DDP) else model.module).load_state_dict(pretrained_model, strict=strict)  ││                                                                                                                      ││ /home/miu/anaconda3/envs/easyvolcap/lib/python3.11/site-packages/torch/nn/modules/module.py:2138 in load_state_dict  ││                                                                                                                      ││ ❱ 2138 │   │   load(self, state_dict)                                                                                ││                                                                                                                      ││ /home/miu/anaconda3/envs/easyvolcap/lib/python3.11/site-packages/torch/nn/modules/module.py:2126 in load             ││                                                                                                                      ││ ❱ 2126 │   │   │   │   │   load(child, child_state_dict, child_prefix)                                               ││                                                                                                                      ││ /home/miu/anaconda3/envs/easyvolcap/lib/python3.11/site-packages/torch/nn/modules/module.py:2131 in load             ││                                                                                                                      ││ ❱ 2131 │   │   │   │   out = hook(module, incompatible_keys)                                                         ││                                                                                                                      ││ /home/miu/anaconda3/envs/easyvolcap/lib/python3.11/site-packages/torch/utils/_contextlib.py:115 in decorate_context  ││                                                                                                                      ││ ❱ 115 │   │   │   return func(*args, **kwargs)                                                                       ││                                                                                                                      ││ /home/miu/mmd/4K4D/easyvolcap/models/samplers/super_charged_r4dv.py:375 in _load_state_dict_post_hook                ││                                                                                                                      ││ ❱ 375 │   │   │   rgbw, cent = l_average_single_frame(i)                                                             ││                                                                                                                      ││ /home/miu/anaconda3/envs/easyvolcap/lib/python3.11/site-packages/torch/utils/_contextlib.py:115 in decorate_context  ││                                                                                                                      ││ ❱ 115 │   │   │   return func(*args, **kwargs)                                                                       ││                                                                                                                      ││ /home/miu/mmd/4K4D/easyvolcap/models/samplers/super_charged_r4dv.py:148 in average_single_frame                      ││                                                                                                                      ││ ❱ 148 │   ibrs_rgbs = sample_geometry_feature_image(                                                                 │╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/home/miu/mmd/4K4D/easyvolcap/utils/enerf_utils.py", line 94, in sample_geometry_feature_image
    # -> B, S, P, 4
    xyz1 = (xyz1[..., None, :, :] @ src_exts.mT)
    xyzs = xyz1[..., :3] @ src_ixts.mT  # B, S, P, 3 @ B, S, 3, 3
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    xy = xyzs[..., :-1] / (xyzs[..., -1:] + 1e-8)  # B, S, P, 2
    x, y = xy.chunk(2, dim=-1)  # B, S, P, 1
RuntimeError: CUDA out of memory. Tried to allocate 180.00 MiB. GPU 0 has a total capacty of 8.00 GiB of which 0 bytes is free. Including non-PyTorch memory, this process has 17179869184.00 GiB memory in use. Of the allocated memory 7.80 GiB is allocated by PyTorch, and 89.26 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

2023-12-23        easyvolcap.model… Caching rgbw and center   0% ━━━━━━━━━━━━━━━━━ 0/150  0:00:03 < -:--:--   ?  it/s s…08:49:46.335766   ->
                  _load_state_dict…
*** The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/home/miu/mmd/4K4D/easyvolcap/utils/enerf_utils.py", line 94, in sample_geometry_feature_image
    # -> B, S, P, 4
    xyz1 = (xyz1[..., None, :, :] @ src_exts.mT)
    xyzs = xyz1[..., :3] @ src_ixts.mT  # B, S, P, 3 @ B, S, 3, 3
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    xy = xyzs[..., :-1] / (xyzs[..., -1:] + 1e-8)  # B, S, P, 2
    x, y = xy.chunk(2, dim=-1)  # B, S, P, 1
RuntimeError: CUDA out of memory. Tried to allocate 180.00 MiB. GPU 0 has a total capacty of 8.00 GiB of which 0 bytes
is free. Including non-PyTorch memory, this process has 17179869184.00 GiB memory in use. Of the allocated memory 7.80
GiB is allocated by PyTorch, and 89.26 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory islarge try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and
PYTORCH_CUDA_ALLOC_CONF

> /home/miu/mmd/4K4D/easyvolcap/models/samplers/super_charged_r4dv.py(148)average_single_frame()
    146
    147     # Compute projected color of every image, using the original size image
--> 148     ibrs_rgbs = sample_geometry_feature_image(
    149         xyz,
    150         src_feat_inps,

```

**Comment by dendenxu** [comment]
Hi @miu200521358 thanks for bringing attention to this. I see that you ran out of GPU memory during the precomputation step (`load_state_dict_post_hook` of `super_charged_r4dv`).
1. The very large memory usage `17179869184.00 GiB` might be a bug on the PyTorch side and it looks like only a logging bug.
2. It is possible to render 4K4D on a 8GB machine. The memory required for the rendering itself is very small. The OOM error you encountered happened during pre-computation. And I assume it's because I set the batch size too high (same as the number of views). I tuned the memory usage for a 12GB machine. You can try modifying this invokation
```python
    # Compute projected color of every image, using the original size image
    ibrs_rgbs = sample_geometry_feature_image(
        xyz,
        src_feat_inps,
        src_exts,
        src_ixts,
        src_inps.new_ones(2, 1),
    )  # B, S, N, 3
```
to wrap it around a for-loop on the second (the `S`) dimension like how I computed the image features later:
```python
    # Compute blending weights from the image features
    bws = torch.cat([sampler.ibr_regressor.rgb_mlp(xyz_ibr_rgbs[:, j:j + 1]) for j in range(xyz_ibr_rgbs.shape[-3])], dim=-3)  # B, S, N, 1
    timer.record('compute blending weights')
```

**Comment by dendenxu** [comment]
@miu200521358 I updated the rendering code to load the DNA-Rendering dataset more efficiently in some recent commits. Could you please try whether this fixed the OOM issue?

**Comment by hhhddddddd** [comment]
Hello, thank you for your warm answer before!

I was trying out Rendering With Minimal Dataset (Only Encoded Videos) using `evc -t test -c configs/projects/realtime4dv/rendering/4k4d_0013_01.yaml,configs/specs/video.yaml`, but I encountered RuntimeError: CUDA out of memory. 

### Environment
GPU: NVIDIA GeForce RTX 3090  (Memory 24GB)

### log
```
(4k4d) xuankai@user-SYS:~/code/4K4D$  evc -t test -c configs/projects/realtime4dv/rendering/4k4d_0013_01.yaml,configs/specs/video.yaml
2024-03-29 19:07:13.357755 easyvolcap.runners -> <module>: Failed to import volumetric_video_viewer.py, missing    __init__.py:10
                           package: imgui_bundle                                                                                 
2024-03-29 19:07:13.361426 __main__ -> preflight: Starting experiment: 4k4d_0013_01, command: test                     main.py:80
2024-0… easyvol… Loading mask bytes for data/renbody/0013_01/masks_libx265 VAL 100% ━━━━━━━ 9,000/9… 0:04:13 < 0:00:00 44.74   p…
19:11:… ->                                                                                                             it/s      
        load_re…                                                                                                                 
2024-0… easyvo… Loading imgs bytes for data/renbody/0013_01/images_libx265 VAL 100% ━━━━━━━ 9,000/9… 1:47:20 < 0:00:00 22.74   p…
21:00:… ->                                                                                                             it/s      
        load_r…                                                                                                                  
2024-03-29 easyvolca… Cropping msks imgs for data/renbody/0013_01 VAL 100% ━━━━━━━━━━ 9,000/9,000 0:40:08 < 0:00:00 92.90 it/s p…
21:40:14.… ->                                                                                                                    
           decode_cr…                                                                                                            
2024-03-29 21:41:42.305437 easyvolcap.runners.visualizers.volumetric_video_visualizer ->        volumetric_video_visualizer.py:80
                           __init__: Visualization output:                                                                       
                           data/result/4k4d_0013_01/{RENDER,DEPTH}                                                               
2024-03-29 21:41:42.374027 easyvolcap.runners.recorders -> __init__: Saved config file to                        recorders.py:105
                           data/record/4k4d_0013_01/4k4d_0013_01_1711719702.yaml                                                 
2024-03-29 21:41:42.376116 __main__ -> launcher: Launching runner for experiment: 4k4d_0013_01                         main.py:50
2024-03-29 21:52:53.630060 easyvolcap.utils.console_utils -> inner: Runtime exception: The following         console_utils.py:391
                           operation failed in the TorchScript interpreter.                                                      
                           Traceback of TorchScript (most recent call last):                                                     
                             File "/home/xuankai/code/4K4D/easyvolcap/utils/enerf_utils.py", line 104, in                        
                           sample_geometry_feature_image                                                                         
                                                                                                                                 
                               # Actual sampling of the image features (along with rgb colors)                                   
                               src_feat_rgb = F.grid_sample(src_feat_rgb.view(-1, C, Hs, Ws), xy.view(-1, 1,                     
                           P, 2), padding_mode=padding_mode).view(B, S, C, P).permute(0, 1, 3, 2)  # BS, C,                      
                           1, P -> B, S, C, P -> B, S, P, C                                                                      
                                              ~~~~~~~~~~~~~ <--- HERE                                                            
                               return src_feat_rgb                                                                               
                             File                                                                                                
                           "/home/xuankai/anaconda3/envs/4k4d/lib/python3.9/site-packages/torch/nn/functiona                     
                           l.py", line 4244, in grid_sample                                                                      
                                   align_corners = False                                                                         
                                                                                                                                 
                               return torch.grid_sampler(input, grid, mode_enum, padding_mode_enum,                              
                           align_corners)                                                                                        
                                      ~~~~~~~~~~~~~~~~~~ <--- HERE                                                               
                           RuntimeError: CUDA out of memory. Tried to allocate 12.00 MiB (GPU 0; 23.69 GiB                       
                           total capacity; 17.06 GiB already allocated; 3.19 MiB free; 23.69 GiB allowed;                        
                           17.12 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory                     
                           try setting max_split_size_mb to avoid fragmentation.  See documentation for                          
                           Memory Management and PYTORCH_CUDA_ALLOC_CONF                                                         
                                                                                                                                 
╭────────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────╮
│ /home/xuankai/code/4K4D/easyvolcap/utils/console_utils.py:388 in inner                                                        │
│                                                                                                                               │
│ ❱ 388 │   │   │   │   return func(*args, **kwargs)                                                                            │
│                                                                                                                               │
│ /home/xuankai/code/4K4D/easyvolcap/scripts/main.py:272 in main                                                                │
│                                                                                                                               │
│ ❱ 272 │   else: globals()[args.type](cfg)  # invoke this (call callable_from_cfg -> call_from_cfg) I: utilize @callable_from_ │
│                                                                                                                               │
│ /home/xuankai/code/4K4D/easyvolcap/engine/registry.py:61 in inner                                                             │
│                                                                                                                               │
│ ❱  61 │   │   return call_from_cfg(func, cfg)                                                                                 │
│                                                                                                                               │
│ /home/xuankai/code/4K4D/easyvolcap/engine/registry.py:52 in call_from_cfg                                                     │
│                                                                                                                               │
│ ❱  52 │   return func(**call_args) # the args of function is prepared.                                                        │
│                                                                                                                               │
│ /home/xuankai/code/4K4D/easyvolcap/scripts/main.py:181 in test                                                                │
│                                                                                                                               │
│ ❱ 181 │   launcher(**kwargs, runner_function=runner.test, runner_object=runner)                                               │
│                                                                                                                               │
│ /home/xuankai/code/4K4D/easyvolcap/scripts/main.py:52 in launcher                                                             │
│                                                                                                                               │
│ ❱  52 │   runner_function()                                                                                                   │
│                                                                                                                               │
│ /home/xuankai/code/4K4D/easyvolcap/runners/volumetric_video_runner.py:274 in test                                             │
│                                                                                                                               │
│ ❱ 274 │   │   epoch = self.load_network()                                                                                     │
│                                                                                                                               │
│ /home/xuankai/code/4K4D/easyvolcap/runners/volumetric_video_runner.py:195 in load_network                                     │
│                                                                                                                               │
│ ❱ 195 │   │   epoch = load_network(model=self.model,  # only loading the network, without recorder?                           │
│                                                                                                                               │
│ /home/xuankai/code/4K4D/easyvolcap/utils/net_utils.py:435 in load_network                                                     │
│                                                                                                                               │
│ ❱ 435 │   (model if not isinstance(model, DDP) else model.module).load_state_dict(pretrained_model, strict=strict)            │
│                                                                                                                               │
│ /home/xuankai/anaconda3/envs/4k4d/lib/python3.9/site-packages/torch/nn/modules/module.py:2027 in load_state_dict              │
│                                                                                                                               │
│ ❱ 2027 │   │   load(self, state_dict)                                                                                         │
│                                                                                                                               │
│ /home/xuankai/anaconda3/envs/4k4d/lib/python3.9/site-packages/torch/nn/modules/module.py:2015 in load                         │
│                                                                                                                               │
│ ❱ 2015 │   │   │   │   │   load(child, child_state_dict, child_prefix)                                                        │
│                                                                                                                               │
│ /home/xuankai/anaconda3/envs/4k4d/lib/python3.9/site-packages/torch/nn/modules/module.py:2020 in load                         │
│                                                                                                                               │
│ ❱ 2020 │   │   │   │   out = hook(module, incompatible_keys)                                                                  │
│                                                                                                                               │
│ /home/xuankai/anaconda3/envs/4k4d/lib/python3.9/site-packages/torch/utils/_contextlib.py:115 in decorate_context              │
│                                                                                                                               │
│ ❱ 115 │   │   │   return func(*args, **kwargs)                                                                                │
│                                                                                                                               │
│ /home/xuankai/code/4K4D/easyvolcap/models/samplers/super_charged_r4dv.py:381 in _load_state_dict_post_hook                    │
│                                                                                                                               │
│ ❱ 381 │   │   │   rgbw, cent = l_average_single_frame(i)                                                                      │
│                                                                                                                               │
│ /home/xuankai/anaconda3/envs/4k4d/lib/python3.9/site-packages/torch/utils/_contextlib.py:115 in decorate_context              │
│                                                                                                                               │
│ ❱ 115 │   │   │   return func(*args, **kwargs)                                                                                │
│                                                                                                                               │
│ /home/xuankai/code/4K4D/easyvolcap/models/samplers/super_charged_r4dv.py:155 in average_single_frame                          │
│                                                                                                                               │
│ ❱ 155 │   ibrs_rgbs = torch.cat([sample_geometry_feature_image(                                                               │
│                                                                                                                               │
│ /home/xuankai/code/4K4D/easyvolcap/models/samplers/super_charged_r4dv.py:155 in <listcomp>                                    │
│                                                                                                                               │
│ ❱ 155 │   ibrs_rgbs = torch.cat([sample_geometry_feature_image(                                                               │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/home/xuankai/code/4K4D/easyvolcap/utils/enerf_utils.py", line 104, in sample_geometry_feature_image

    # Actual sampling of the image features (along with rgb colors)
    src_feat_rgb = F.grid_sample(src_feat_rgb.view(-1, C, Hs, Ws), xy.view(-1, 1, P, 2), padding_mode=padding_mode).view(B, S, C, P).permute(0, 1, 3, 2)  # BS, C, 1, P -> B, S, C, P -> B, S, P, C
                   ~~~~~~~~~~~~~ <--- HERE
    return src_feat_rgb
  File "/home/xuankai/anaconda3/envs/4k4d/lib/python3.9/site-packages/torch/nn/functional.py", line 4244, in grid_sample
        align_corners = False

    return torch.grid_sampler(input, grid, mode_enum, padding_mode_enum, align_corners)
           ~~~~~~~~~~~~~~~~~~ <--- HERE
RuntimeError: CUDA out of memory. Tried to allocate 12.00 MiB (GPU 0; 23.69 GiB total capacity; 17.06 GiB already allocated; 3.19 MiB free; 23.69 GiB allowed; 17.12 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

2024-03-29          easyvolcap.models.s… Caching rgbw and center  48% ━━━━━━━━━╺━━━━━━━━━ 72/150  0:11:02 < 0:06:32 0.199 it/s s…
21:52:55.303285     ->                                                                                                           
                    _load_state_dict_po…                                                                                         
*** The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/home/xuankai/code/4K4D/easyvolcap/utils/enerf_utils.py", line 104, in sample_geometry_feature_image

    # Actual sampling of the image features (along with rgb colors)
    src_feat_rgb = F.grid_sample(src_feat_rgb.view(-1, C, Hs, Ws), xy.view(-1, 1, P, 2), padding_mode=padding_mode).view(B, S, C,
P).permute(0, 1, 3, 2)  # BS, C, 1, P -> B, S, C, P -> B, S, P, C
                   ~~~~~~~~~~~~~ <--- HERE
    return src_feat_rgb
  File "/home/xuankai/anaconda3/envs/4k4d/lib/python3.9/site-packages/torch/nn/functional.py", line 4244, in grid_sample
        align_corners = False

    return torch.grid_sampler(input, grid, mode_enum, padding_mode_enum, align_corners)
           ~~~~~~~~~~~~~~~~~~ <--- HERE
RuntimeError: CUDA out of memory. Tried to allocate 12.00 MiB (GPU 0; 23.69 GiB total capacity; 17.06 GiB already allocated; 3.19
MiB free; 23.69 GiB allowed; 17.12 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting 
max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

> /home/xuankai/code/4K4D/easyvolcap/models/samplers/super_charged_r4dv.py(155)<listcomp>()
    153 
    154     # Compute projected color of every image, using the original size image
--> 155     ibrs_rgbs = torch.cat([sample_geometry_feature_image(
    156         xyz,
    157         src_feat_inps[:, i:i + 1],

(Pdbr) Killed
(4k4d) xuankai@user-SYS:~/code/4K4D$ 
```

Do you have any suggestions for my problems?
